package entidades;
// Generated 11-sep-2015 8:21:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Admision generated by hbm2java
 */
public class Admision  implements java.io.Serializable {


     private Integer idAdmision;
     private GradoInstruccion gradoInstruccion;
     private HistoriaClinica historiaClinica;
     private Persona persona;
     private Ubigeo ubigeo;
     private UnidadMilitar unidadMilitar;
     private Usuario usuario;
     private Date horaIngreso;
     private Date horaSalida;
     private Date fechaReg;

    public Admision() {
    }

	
    public Admision(GradoInstruccion gradoInstruccion, HistoriaClinica historiaClinica, Persona persona, Ubigeo ubigeo, UnidadMilitar unidadMilitar, Usuario usuario) {
        this.gradoInstruccion = gradoInstruccion;
        this.historiaClinica = historiaClinica;
        this.persona = persona;
        this.ubigeo = ubigeo;
        this.unidadMilitar = unidadMilitar;
        this.usuario = usuario;
    }
    public Admision(GradoInstruccion gradoInstruccion, HistoriaClinica historiaClinica, Persona persona, Ubigeo ubigeo, UnidadMilitar unidadMilitar, Usuario usuario, Date horaIngreso, Date horaSalida, Date fechaReg) {
       this.gradoInstruccion = gradoInstruccion;
       this.historiaClinica = historiaClinica;
       this.persona = persona;
       this.ubigeo = ubigeo;
       this.unidadMilitar = unidadMilitar;
       this.usuario = usuario;
       this.horaIngreso = horaIngreso;
       this.horaSalida = horaSalida;
       this.fechaReg = fechaReg;
    }
   
    public Integer getIdAdmision() {
        return this.idAdmision;
    }
    
    public void setIdAdmision(Integer idAdmision) {
        this.idAdmision = idAdmision;
    }
    public GradoInstruccion getGradoInstruccion() {
        return this.gradoInstruccion;
    }
    
    public void setGradoInstruccion(GradoInstruccion gradoInstruccion) {
        this.gradoInstruccion = gradoInstruccion;
    }
    public HistoriaClinica getHistoriaClinica() {
        return this.historiaClinica;
    }
    
    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Ubigeo getUbigeo() {
        return this.ubigeo;
    }
    
    public void setUbigeo(Ubigeo ubigeo) {
        this.ubigeo = ubigeo;
    }
    public UnidadMilitar getUnidadMilitar() {
        return this.unidadMilitar;
    }
    
    public void setUnidadMilitar(UnidadMilitar unidadMilitar) {
        this.unidadMilitar = unidadMilitar;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getHoraIngreso() {
        return this.horaIngreso;
    }
    
    public void setHoraIngreso(Date horaIngreso) {
        this.horaIngreso = horaIngreso;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }




}


