package entidades;
// Generated 25-ago-2015 21:41:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alergia generated by hbm2java
 */
public class Alergia  implements java.io.Serializable {


     private Integer idAlergia;
     private Medicamento medicamento;
     private Persona persona;
     private String motivo;
     private String tiempoDosis;
     private String observacion;
     private Date fechaReg;

    public Alergia() {
    }

	
    public Alergia(Medicamento medicamento, Persona persona) {
        this.medicamento = medicamento;
        this.persona = persona;
    }
    public Alergia(Medicamento medicamento, Persona persona, String motivo, String tiempoDosis, String observacion, Date fechaReg) {
       this.medicamento = medicamento;
       this.persona = persona;
       this.motivo = motivo;
       this.tiempoDosis = tiempoDosis;
       this.observacion = observacion;
       this.fechaReg = fechaReg;
    }
   
    public Integer getIdAlergia() {
        return this.idAlergia;
    }
    
    public void setIdAlergia(Integer idAlergia) {
        this.idAlergia = idAlergia;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getTiempoDosis() {
        return this.tiempoDosis;
    }
    
    public void setTiempoDosis(String tiempoDosis) {
        this.tiempoDosis = tiempoDosis;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }




}


