package entidades;
// Generated 25-ago-2015 21:41:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Antecedente generated by hbm2java
 */
public class Antecedente  implements java.io.Serializable {


     private Integer idAntecedente;
     private Cie10 cie10;
     private Persona persona;
     private Usuario usuario;
     private String descripcion;
     private String tipoAntecedente;
     private Date fechaReg;

    public Antecedente() {
    }

	
    public Antecedente(Cie10 cie10, Persona persona, Usuario usuario) {
        this.cie10 = cie10;
        this.persona = persona;
        this.usuario = usuario;
    }
    public Antecedente(Cie10 cie10, Persona persona, Usuario usuario, String descripcion, String tipoAntecedente, Date fechaReg) {
       this.cie10 = cie10;
       this.persona = persona;
       this.usuario = usuario;
       this.descripcion = descripcion;
       this.tipoAntecedente = tipoAntecedente;
       this.fechaReg = fechaReg;
    }
   
    public Integer getIdAntecedente() {
        return this.idAntecedente;
    }
    
    public void setIdAntecedente(Integer idAntecedente) {
        this.idAntecedente = idAntecedente;
    }
    public Cie10 getCie10() {
        return this.cie10;
    }
    
    public void setCie10(Cie10 cie10) {
        this.cie10 = cie10;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipoAntecedente() {
        return this.tipoAntecedente;
    }
    
    public void setTipoAntecedente(String tipoAntecedente) {
        this.tipoAntecedente = tipoAntecedente;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }




}


