package entidades;
// Generated 06-sep-2015 6:46:45 by Hibernate Tools 4.3.1



/**
 * CentroSaludServicioEspecialidad generated by hbm2java
 */
public class CentroSaludServicioEspecialidad  implements java.io.Serializable {


     private Integer idCentroSaludEspecialidad;
     private CentroSalud centroSalud;
     private ServicioEspecialidad servicioEspecialidad;
     private String estado;

    public CentroSaludServicioEspecialidad() {
    }

	
    public CentroSaludServicioEspecialidad(CentroSalud centroSalud, ServicioEspecialidad servicioEspecialidad) {
        this.centroSalud = centroSalud;
        this.servicioEspecialidad = servicioEspecialidad;
    }
    public CentroSaludServicioEspecialidad(CentroSalud centroSalud, ServicioEspecialidad servicioEspecialidad, String estado) {
       this.centroSalud = centroSalud;
       this.servicioEspecialidad = servicioEspecialidad;
       this.estado = estado;
    }
   
    public Integer getIdCentroSaludEspecialidad() {
        return this.idCentroSaludEspecialidad;
    }
    
    public void setIdCentroSaludEspecialidad(Integer idCentroSaludEspecialidad) {
        this.idCentroSaludEspecialidad = idCentroSaludEspecialidad;
    }
    public CentroSalud getCentroSalud() {
        return this.centroSalud;
    }
    
    public void setCentroSalud(CentroSalud centroSalud) {
        this.centroSalud = centroSalud;
    }
    public ServicioEspecialidad getServicioEspecialidad() {
        return this.servicioEspecialidad;
    }
    
    public void setServicioEspecialidad(ServicioEspecialidad servicioEspecialidad) {
        this.servicioEspecialidad = servicioEspecialidad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


