package entidades;
// Generated 25-ago-2015 21:41:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CentroSalud generated by hbm2java
 */
public class CentroSalud  implements java.io.Serializable {


     private Integer idCentroSalud;
     private String centroSalud;
     private String nivel;
     private Set<CentroSaludServicioEspecialdiad> centroSaludServicioEspecialdiads = new HashSet<CentroSaludServicioEspecialdiad>(0);

    public CentroSalud() {
    }

	
    public CentroSalud(String centroSalud) {
        this.centroSalud = centroSalud;
    }
    public CentroSalud(String centroSalud, String nivel, Set<CentroSaludServicioEspecialdiad> centroSaludServicioEspecialdiads) {
       this.centroSalud = centroSalud;
       this.nivel = nivel;
       this.centroSaludServicioEspecialdiads = centroSaludServicioEspecialdiads;
    }
   
    public Integer getIdCentroSalud() {
        return this.idCentroSalud;
    }
    
    public void setIdCentroSalud(Integer idCentroSalud) {
        this.idCentroSalud = idCentroSalud;
    }
    public String getCentroSalud() {
        return this.centroSalud;
    }
    
    public void setCentroSalud(String centroSalud) {
        this.centroSalud = centroSalud;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public Set<CentroSaludServicioEspecialdiad> getCentroSaludServicioEspecialdiads() {
        return this.centroSaludServicioEspecialdiads;
    }
    
    public void setCentroSaludServicioEspecialdiads(Set<CentroSaludServicioEspecialdiad> centroSaludServicioEspecialdiads) {
        this.centroSaludServicioEspecialdiads = centroSaludServicioEspecialdiads;
    }




}


