package entidades;
// Generated 11-sep-2015 8:21:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CentroSalud generated by hbm2java
 */
public class CentroSalud  implements java.io.Serializable {


     private Integer idCentroSalud;
     private String centroSalud;
     private String nivel;
     private Set<CentroSaludServicioEspecialidad> centroSaludServicioEspecialidads = new HashSet<CentroSaludServicioEspecialidad>(0);

    public CentroSalud() {
    }

	
    public CentroSalud(String centroSalud) {
        this.centroSalud = centroSalud;
    }
    public CentroSalud(String centroSalud, String nivel, Set<CentroSaludServicioEspecialidad> centroSaludServicioEspecialidads) {
       this.centroSalud = centroSalud;
       this.nivel = nivel;
       this.centroSaludServicioEspecialidads = centroSaludServicioEspecialidads;
    }
   
    public Integer getIdCentroSalud() {
        return this.idCentroSalud;
    }
    
    public void setIdCentroSalud(Integer idCentroSalud) {
        this.idCentroSalud = idCentroSalud;
    }
    public String getCentroSalud() {
        return this.centroSalud;
    }
    
    public void setCentroSalud(String centroSalud) {
        this.centroSalud = centroSalud;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public Set<CentroSaludServicioEspecialidad> getCentroSaludServicioEspecialidads() {
        return this.centroSaludServicioEspecialidads;
    }
    
    public void setCentroSaludServicioEspecialidads(Set<CentroSaludServicioEspecialidad> centroSaludServicioEspecialidads) {
        this.centroSaludServicioEspecialidads = centroSaludServicioEspecialidads;
    }




}


