package entidades;
// Generated 06-sep-2015 6:46:45 by Hibernate Tools 4.3.1



/**
 * DetalleHis generated by hbm2java
 */
public class DetalleHis  implements java.io.Serializable {


     private Integer idDetalleHis;
     private Cie10 cie10;
     private His his;
     private Usuario usuario;
     private String tratamiento;
     private String aparatoConprometido;

    public DetalleHis() {
    }

	
    public DetalleHis(Cie10 cie10, His his, Usuario usuario) {
        this.cie10 = cie10;
        this.his = his;
        this.usuario = usuario;
    }
    public DetalleHis(Cie10 cie10, His his, Usuario usuario, String tratamiento, String aparatoConprometido) {
       this.cie10 = cie10;
       this.his = his;
       this.usuario = usuario;
       this.tratamiento = tratamiento;
       this.aparatoConprometido = aparatoConprometido;
    }
   
    public Integer getIdDetalleHis() {
        return this.idDetalleHis;
    }
    
    public void setIdDetalleHis(Integer idDetalleHis) {
        this.idDetalleHis = idDetalleHis;
    }
    public Cie10 getCie10() {
        return this.cie10;
    }
    
    public void setCie10(Cie10 cie10) {
        this.cie10 = cie10;
    }
    public His getHis() {
        return this.his;
    }
    
    public void setHis(His his) {
        this.his = his;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }
    public String getAparatoConprometido() {
        return this.aparatoConprometido;
    }
    
    public void setAparatoConprometido(String aparatoConprometido) {
        this.aparatoConprometido = aparatoConprometido;
    }




}


