package entidades;
// Generated 25-ago-2015 21:41:00 by Hibernate Tools 4.3.1



/**
 * DetalleReceta generated by hbm2java
 */
public class DetalleReceta  implements java.io.Serializable {


     private Integer idDetalleReceta;
     private Medicamento medicamento;
     private Recetamedica recetamedica;
     private String frecuencia;
     private String dosis;
     private String via;
     private String duracion;

    public DetalleReceta() {
    }

	
    public DetalleReceta(Medicamento medicamento, Recetamedica recetamedica) {
        this.medicamento = medicamento;
        this.recetamedica = recetamedica;
    }
    public DetalleReceta(Medicamento medicamento, Recetamedica recetamedica, String frecuencia, String dosis, String via, String duracion) {
       this.medicamento = medicamento;
       this.recetamedica = recetamedica;
       this.frecuencia = frecuencia;
       this.dosis = dosis;
       this.via = via;
       this.duracion = duracion;
    }
   
    public Integer getIdDetalleReceta() {
        return this.idDetalleReceta;
    }
    
    public void setIdDetalleReceta(Integer idDetalleReceta) {
        this.idDetalleReceta = idDetalleReceta;
    }
    public Medicamento getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }
    public Recetamedica getRecetamedica() {
        return this.recetamedica;
    }
    
    public void setRecetamedica(Recetamedica recetamedica) {
        this.recetamedica = recetamedica;
    }
    public String getFrecuencia() {
        return this.frecuencia;
    }
    
    public void setFrecuencia(String frecuencia) {
        this.frecuencia = frecuencia;
    }
    public String getDosis() {
        return this.dosis;
    }
    
    public void setDosis(String dosis) {
        this.dosis = dosis;
    }
    public String getVia() {
        return this.via;
    }
    
    public void setVia(String via) {
        this.via = via;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }




}


