package entidades;
// Generated 06-sep-2015 6:46:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExamenFisico generated by hbm2java
 */
public class ExamenFisico  implements java.io.Serializable {


     private Integer idExamenFisico;
     private HistoriaClinica historiaClinica;
     private Usuario usuario;
     private Date horaIngreso;
     private String pa;
     private String fc;
     private String t;
     private String peso;
     private String talla;
     private String fr;
     private String so2;
     private Date horaSalida;
     private Date fechaReg;

    public ExamenFisico() {
    }

	
    public ExamenFisico(HistoriaClinica historiaClinica, Usuario usuario) {
        this.historiaClinica = historiaClinica;
        this.usuario = usuario;
    }
    public ExamenFisico(HistoriaClinica historiaClinica, Usuario usuario, Date horaIngreso, String pa, String fc, String t, String peso, String talla, String fr, String so2, Date horaSalida, Date fechaReg) {
       this.historiaClinica = historiaClinica;
       this.usuario = usuario;
       this.horaIngreso = horaIngreso;
       this.pa = pa;
       this.fc = fc;
       this.t = t;
       this.peso = peso;
       this.talla = talla;
       this.fr = fr;
       this.so2 = so2;
       this.horaSalida = horaSalida;
       this.fechaReg = fechaReg;
    }
   
    public Integer getIdExamenFisico() {
        return this.idExamenFisico;
    }
    
    public void setIdExamenFisico(Integer idExamenFisico) {
        this.idExamenFisico = idExamenFisico;
    }
    public HistoriaClinica getHistoriaClinica() {
        return this.historiaClinica;
    }
    
    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getHoraIngreso() {
        return this.horaIngreso;
    }
    
    public void setHoraIngreso(Date horaIngreso) {
        this.horaIngreso = horaIngreso;
    }
    public String getPa() {
        return this.pa;
    }
    
    public void setPa(String pa) {
        this.pa = pa;
    }
    public String getFc() {
        return this.fc;
    }
    
    public void setFc(String fc) {
        this.fc = fc;
    }
    public String getT() {
        return this.t;
    }
    
    public void setT(String t) {
        this.t = t;
    }
    public String getPeso() {
        return this.peso;
    }
    
    public void setPeso(String peso) {
        this.peso = peso;
    }
    public String getTalla() {
        return this.talla;
    }
    
    public void setTalla(String talla) {
        this.talla = talla;
    }
    public String getFr() {
        return this.fr;
    }
    
    public void setFr(String fr) {
        this.fr = fr;
    }
    public String getSo2() {
        return this.so2;
    }
    
    public void setSo2(String so2) {
        this.so2 = so2;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }




}


