package entidades;
// Generated 25-ago-2015 21:41:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * His generated by hbm2java
 */
public class His  implements java.io.Serializable {


     private Integer idHis;
     private HistoriaClinica historiaClinica;
     private Usuario usuario;
     private Date horaIngreso;
     private String signos;
     private String sintomas;
     private String tipoDescanso;
     private Integer diasDescanso;
     private String urgencia;
     private String evacuacion;
     private String interconsulta;
     private String examenAuxilidar;
     private Set<DetalleHis> detalleHises = new HashSet<DetalleHis>(0);
     private Set<Recetamedica> recetamedicas = new HashSet<Recetamedica>(0);

    public His() {
    }

	
    public His(HistoriaClinica historiaClinica, Usuario usuario) {
        this.historiaClinica = historiaClinica;
        this.usuario = usuario;
    }
    public His(HistoriaClinica historiaClinica, Usuario usuario, Date horaIngreso, String signos, String sintomas, String tipoDescanso, Integer diasDescanso, String urgencia, String evacuacion, String interconsulta, String examenAuxilidar, Set<DetalleHis> detalleHises, Set<Recetamedica> recetamedicas) {
       this.historiaClinica = historiaClinica;
       this.usuario = usuario;
       this.horaIngreso = horaIngreso;
       this.signos = signos;
       this.sintomas = sintomas;
       this.tipoDescanso = tipoDescanso;
       this.diasDescanso = diasDescanso;
       this.urgencia = urgencia;
       this.evacuacion = evacuacion;
       this.interconsulta = interconsulta;
       this.examenAuxilidar = examenAuxilidar;
       this.detalleHises = detalleHises;
       this.recetamedicas = recetamedicas;
    }
   
    public Integer getIdHis() {
        return this.idHis;
    }
    
    public void setIdHis(Integer idHis) {
        this.idHis = idHis;
    }
    public HistoriaClinica getHistoriaClinica() {
        return this.historiaClinica;
    }
    
    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getHoraIngreso() {
        return this.horaIngreso;
    }
    
    public void setHoraIngreso(Date horaIngreso) {
        this.horaIngreso = horaIngreso;
    }
    public String getSignos() {
        return this.signos;
    }
    
    public void setSignos(String signos) {
        this.signos = signos;
    }
    public String getSintomas() {
        return this.sintomas;
    }
    
    public void setSintomas(String sintomas) {
        this.sintomas = sintomas;
    }
    public String getTipoDescanso() {
        return this.tipoDescanso;
    }
    
    public void setTipoDescanso(String tipoDescanso) {
        this.tipoDescanso = tipoDescanso;
    }
    public Integer getDiasDescanso() {
        return this.diasDescanso;
    }
    
    public void setDiasDescanso(Integer diasDescanso) {
        this.diasDescanso = diasDescanso;
    }
    public String getUrgencia() {
        return this.urgencia;
    }
    
    public void setUrgencia(String urgencia) {
        this.urgencia = urgencia;
    }
    public String getEvacuacion() {
        return this.evacuacion;
    }
    
    public void setEvacuacion(String evacuacion) {
        this.evacuacion = evacuacion;
    }
    public String getInterconsulta() {
        return this.interconsulta;
    }
    
    public void setInterconsulta(String interconsulta) {
        this.interconsulta = interconsulta;
    }
    public String getExamenAuxilidar() {
        return this.examenAuxilidar;
    }
    
    public void setExamenAuxilidar(String examenAuxilidar) {
        this.examenAuxilidar = examenAuxilidar;
    }
    public Set<DetalleHis> getDetalleHises() {
        return this.detalleHises;
    }
    
    public void setDetalleHises(Set<DetalleHis> detalleHises) {
        this.detalleHises = detalleHises;
    }
    public Set<Recetamedica> getRecetamedicas() {
        return this.recetamedicas;
    }
    
    public void setRecetamedicas(Set<Recetamedica> recetamedicas) {
        this.recetamedicas = recetamedicas;
    }




}


