package entidades;
// Generated 25-ago-2015 21:41:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HistoriaClinica generated by hbm2java
 */
public class HistoriaClinica  implements java.io.Serializable {


     private Integer idHistoriaClinica;
     private HistoriaClinica historiaClinica;
     private Persona persona;
     private Usuario usuario;
     private Integer numEpisodio;
     private String estado;
     private Date fechaReg;
     private Set<ExamenFisico> examenFisicos = new HashSet<ExamenFisico>(0);
     private Set<HistoriaClinica> historiaClinicas = new HashSet<HistoriaClinica>(0);
     private Set<His> hises = new HashSet<His>(0);
     private Set<Topico> topicos = new HashSet<Topico>(0);
     private Set<Admision> admisions = new HashSet<Admision>(0);

    public HistoriaClinica() {
    }

	
    public HistoriaClinica(Persona persona, Usuario usuario) {
        this.persona = persona;
        this.usuario = usuario;
    }
    public HistoriaClinica(HistoriaClinica historiaClinica, Persona persona, Usuario usuario, Integer numEpisodio, String estado, Date fechaReg, Set<ExamenFisico> examenFisicos, Set<HistoriaClinica> historiaClinicas, Set<His> hises, Set<Topico> topicos, Set<Admision> admisions) {
       this.historiaClinica = historiaClinica;
       this.persona = persona;
       this.usuario = usuario;
       this.numEpisodio = numEpisodio;
       this.estado = estado;
       this.fechaReg = fechaReg;
       this.examenFisicos = examenFisicos;
       this.historiaClinicas = historiaClinicas;
       this.hises = hises;
       this.topicos = topicos;
       this.admisions = admisions;
    }
   
    public Integer getIdHistoriaClinica() {
        return this.idHistoriaClinica;
    }
    
    public void setIdHistoriaClinica(Integer idHistoriaClinica) {
        this.idHistoriaClinica = idHistoriaClinica;
    }
    public HistoriaClinica getHistoriaClinica() {
        return this.historiaClinica;
    }
    
    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getNumEpisodio() {
        return this.numEpisodio;
    }
    
    public void setNumEpisodio(Integer numEpisodio) {
        this.numEpisodio = numEpisodio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<ExamenFisico> getExamenFisicos() {
        return this.examenFisicos;
    }
    
    public void setExamenFisicos(Set<ExamenFisico> examenFisicos) {
        this.examenFisicos = examenFisicos;
    }
    public Set<HistoriaClinica> getHistoriaClinicas() {
        return this.historiaClinicas;
    }
    
    public void setHistoriaClinicas(Set<HistoriaClinica> historiaClinicas) {
        this.historiaClinicas = historiaClinicas;
    }
    public Set<His> getHises() {
        return this.hises;
    }
    
    public void setHises(Set<His> hises) {
        this.hises = hises;
    }
    public Set<Topico> getTopicos() {
        return this.topicos;
    }
    
    public void setTopicos(Set<Topico> topicos) {
        this.topicos = topicos;
    }
    public Set<Admision> getAdmisions() {
        return this.admisions;
    }
    
    public void setAdmisions(Set<Admision> admisions) {
        this.admisions = admisions;
    }




}


