package entidades;
// Generated 06-sep-2015 6:46:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medicamento generated by hbm2java
 */
public class Medicamento  implements java.io.Serializable {


     private Integer idMedicamento;
     private String categoria;
     private String tipoMedicamento;
     private String medicamento;
     private Set<Alergia> alergias = new HashSet<Alergia>(0);
     private Set<DetalleReceta> detalleRecetas = new HashSet<DetalleReceta>(0);

    public Medicamento() {
    }

    public Medicamento(String categoria, String tipoMedicamento, String medicamento, Set<Alergia> alergias, Set<DetalleReceta> detalleRecetas) {
       this.categoria = categoria;
       this.tipoMedicamento = tipoMedicamento;
       this.medicamento = medicamento;
       this.alergias = alergias;
       this.detalleRecetas = detalleRecetas;
    }
   
    public Integer getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(Integer idMedicamento) {
        this.idMedicamento = idMedicamento;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getTipoMedicamento() {
        return this.tipoMedicamento;
    }
    
    public void setTipoMedicamento(String tipoMedicamento) {
        this.tipoMedicamento = tipoMedicamento;
    }
    public String getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(String medicamento) {
        this.medicamento = medicamento;
    }
    public Set<Alergia> getAlergias() {
        return this.alergias;
    }
    
    public void setAlergias(Set<Alergia> alergias) {
        this.alergias = alergias;
    }
    public Set<DetalleReceta> getDetalleRecetas() {
        return this.detalleRecetas;
    }
    
    public void setDetalleRecetas(Set<DetalleReceta> detalleRecetas) {
        this.detalleRecetas = detalleRecetas;
    }




}


