package entidades;
// Generated 11-sep-2015 8:21:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private GradoInstruccion gradoInstruccion;
     private Ubigeo ubigeo;
     private Usuario usuario;
     private String nombres;
     private String apellidoMaterno;
     private String apellidoPaterno;
     private Character sexo;
     private Date fechaNac;
     private Character estadoCivil;
     private String direccionActual;
     private Integer dni;
     private String email;
     private String celular;
     private String ocupacionOficio;
     private String foto;
     private String tipoSangre;
     private Integer numeroAdministrativo;
     private String estado;
     private Date fechaReg;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Alergia> alergias = new HashSet<Alergia>(0);
     private Set<Sexualidad> sexualidads = new HashSet<Sexualidad>(0);
     private Set<Admision> admisions = new HashSet<Admision>(0);
     private Set<PersonaTipoPersona> personaTipoPersonas = new HashSet<PersonaTipoPersona>(0);
     private Set<HistoriaClinica> historiaClinicas = new HashSet<HistoriaClinica>(0);
     private Set<Antecedente> antecedentes = new HashSet<Antecedente>(0);

    public Persona() {
    }

	
    public Persona(GradoInstruccion gradoInstruccion, Ubigeo ubigeo, Usuario usuario, String nombres) {
        this.gradoInstruccion = gradoInstruccion;
        this.ubigeo = ubigeo;
        this.usuario = usuario;
        this.nombres = nombres;
    }
    public Persona(GradoInstruccion gradoInstruccion, Ubigeo ubigeo, Usuario usuario, String nombres, String apellidoMaterno, String apellidoPaterno, Character sexo, Date fechaNac, Character estadoCivil, String direccionActual, Integer dni, String email, String celular, String ocupacionOficio, String foto, String tipoSangre, Integer numeroAdministrativo, String estado, Date fechaReg, Set<Usuario> usuarios, Set<Alergia> alergias, Set<Sexualidad> sexualidads, Set<Admision> admisions, Set<PersonaTipoPersona> personaTipoPersonas, Set<HistoriaClinica> historiaClinicas, Set<Antecedente> antecedentes) {
       this.gradoInstruccion = gradoInstruccion;
       this.ubigeo = ubigeo;
       this.usuario = usuario;
       this.nombres = nombres;
       this.apellidoMaterno = apellidoMaterno;
       this.apellidoPaterno = apellidoPaterno;
       this.sexo = sexo;
       this.fechaNac = fechaNac;
       this.estadoCivil = estadoCivil;
       this.direccionActual = direccionActual;
       this.dni = dni;
       this.email = email;
       this.celular = celular;
       this.ocupacionOficio = ocupacionOficio;
       this.foto = foto;
       this.tipoSangre = tipoSangre;
       this.numeroAdministrativo = numeroAdministrativo;
       this.estado = estado;
       this.fechaReg = fechaReg;
       this.usuarios = usuarios;
       this.alergias = alergias;
       this.sexualidads = sexualidads;
       this.admisions = admisions;
       this.personaTipoPersonas = personaTipoPersonas;
       this.historiaClinicas = historiaClinicas;
       this.antecedentes = antecedentes;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public GradoInstruccion getGradoInstruccion() {
        return this.gradoInstruccion;
    }
    
    public void setGradoInstruccion(GradoInstruccion gradoInstruccion) {
        this.gradoInstruccion = gradoInstruccion;
    }
    public Ubigeo getUbigeo() {
        return this.ubigeo;
    }
    
    public void setUbigeo(Ubigeo ubigeo) {
        this.ubigeo = ubigeo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Character getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(Character estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getDireccionActual() {
        return this.direccionActual;
    }
    
    public void setDireccionActual(String direccionActual) {
        this.direccionActual = direccionActual;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getOcupacionOficio() {
        return this.ocupacionOficio;
    }
    
    public void setOcupacionOficio(String ocupacionOficio) {
        this.ocupacionOficio = ocupacionOficio;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public Integer getNumeroAdministrativo() {
        return this.numeroAdministrativo;
    }
    
    public void setNumeroAdministrativo(Integer numeroAdministrativo) {
        this.numeroAdministrativo = numeroAdministrativo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Alergia> getAlergias() {
        return this.alergias;
    }
    
    public void setAlergias(Set<Alergia> alergias) {
        this.alergias = alergias;
    }
    public Set<Sexualidad> getSexualidads() {
        return this.sexualidads;
    }
    
    public void setSexualidads(Set<Sexualidad> sexualidads) {
        this.sexualidads = sexualidads;
    }
    public Set<Admision> getAdmisions() {
        return this.admisions;
    }
    
    public void setAdmisions(Set<Admision> admisions) {
        this.admisions = admisions;
    }
    public Set<PersonaTipoPersona> getPersonaTipoPersonas() {
        return this.personaTipoPersonas;
    }
    
    public void setPersonaTipoPersonas(Set<PersonaTipoPersona> personaTipoPersonas) {
        this.personaTipoPersonas = personaTipoPersonas;
    }
    public Set<HistoriaClinica> getHistoriaClinicas() {
        return this.historiaClinicas;
    }
    
    public void setHistoriaClinicas(Set<HistoriaClinica> historiaClinicas) {
        this.historiaClinicas = historiaClinicas;
    }
    public Set<Antecedente> getAntecedentes() {
        return this.antecedentes;
    }
    
    public void setAntecedentes(Set<Antecedente> antecedentes) {
        this.antecedentes = antecedentes;
    }




}


