package entidades;
// Generated 11-sep-2015 8:21:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recetamedica generated by hbm2java
 */
public class Recetamedica  implements java.io.Serializable {


     private Integer idRecetaMedica;
     private His his;
     private Usuario usuario;
     private Date fechaReg;
     private Set<Topico> topicos = new HashSet<Topico>(0);
     private Set<DetalleReceta> detalleRecetas = new HashSet<DetalleReceta>(0);

    public Recetamedica() {
    }

	
    public Recetamedica(His his, Usuario usuario) {
        this.his = his;
        this.usuario = usuario;
    }
    public Recetamedica(His his, Usuario usuario, Date fechaReg, Set<Topico> topicos, Set<DetalleReceta> detalleRecetas) {
       this.his = his;
       this.usuario = usuario;
       this.fechaReg = fechaReg;
       this.topicos = topicos;
       this.detalleRecetas = detalleRecetas;
    }
   
    public Integer getIdRecetaMedica() {
        return this.idRecetaMedica;
    }
    
    public void setIdRecetaMedica(Integer idRecetaMedica) {
        this.idRecetaMedica = idRecetaMedica;
    }
    public His getHis() {
        return this.his;
    }
    
    public void setHis(His his) {
        this.his = his;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<Topico> getTopicos() {
        return this.topicos;
    }
    
    public void setTopicos(Set<Topico> topicos) {
        this.topicos = topicos;
    }
    public Set<DetalleReceta> getDetalleRecetas() {
        return this.detalleRecetas;
    }
    
    public void setDetalleRecetas(Set<DetalleReceta> detalleRecetas) {
        this.detalleRecetas = detalleRecetas;
    }




}


