package entidades;
// Generated 11-sep-2015 8:21:55 by Hibernate Tools 4.3.1



/**
 * RolServicio generated by hbm2java
 */
public class RolServicio  implements java.io.Serializable {


     private Integer idRolServicio;
     private Rol rol;
     private ServicioEspecialidad servicioEspecialidad;

    public RolServicio() {
    }

    public RolServicio(Rol rol, ServicioEspecialidad servicioEspecialidad) {
       this.rol = rol;
       this.servicioEspecialidad = servicioEspecialidad;
    }
   
    public Integer getIdRolServicio() {
        return this.idRolServicio;
    }
    
    public void setIdRolServicio(Integer idRolServicio) {
        this.idRolServicio = idRolServicio;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public ServicioEspecialidad getServicioEspecialidad() {
        return this.servicioEspecialidad;
    }
    
    public void setServicioEspecialidad(ServicioEspecialidad servicioEspecialidad) {
        this.servicioEspecialidad = servicioEspecialidad;
    }




}


