package entidades;
// Generated 25-ago-2015 21:41:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ServicioEspecialidad generated by hbm2java
 */
public class ServicioEspecialidad  implements java.io.Serializable {


     private Integer idServicioEspecialidad;
     private Integer codServicio;
     private Integer codEpsecialidad;
     private String nombre;
     private Set<CentroSaludServicioEspecialdiad> centroSaludServicioEspecialdiads = new HashSet<CentroSaludServicioEspecialdiad>(0);
     private Set<PersonaTipoPersona> personaTipoPersonas = new HashSet<PersonaTipoPersona>(0);
     private Set<RolServicio> rolServicios = new HashSet<RolServicio>(0);

    public ServicioEspecialidad() {
    }

    public ServicioEspecialidad(Integer codServicio, Integer codEpsecialidad, String nombre, Set<CentroSaludServicioEspecialdiad> centroSaludServicioEspecialdiads, Set<PersonaTipoPersona> personaTipoPersonas, Set<RolServicio> rolServicios) {
       this.codServicio = codServicio;
       this.codEpsecialidad = codEpsecialidad;
       this.nombre = nombre;
       this.centroSaludServicioEspecialdiads = centroSaludServicioEspecialdiads;
       this.personaTipoPersonas = personaTipoPersonas;
       this.rolServicios = rolServicios;
    }
   
    public Integer getIdServicioEspecialidad() {
        return this.idServicioEspecialidad;
    }
    
    public void setIdServicioEspecialidad(Integer idServicioEspecialidad) {
        this.idServicioEspecialidad = idServicioEspecialidad;
    }
    public Integer getCodServicio() {
        return this.codServicio;
    }
    
    public void setCodServicio(Integer codServicio) {
        this.codServicio = codServicio;
    }
    public Integer getCodEpsecialidad() {
        return this.codEpsecialidad;
    }
    
    public void setCodEpsecialidad(Integer codEpsecialidad) {
        this.codEpsecialidad = codEpsecialidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<CentroSaludServicioEspecialdiad> getCentroSaludServicioEspecialdiads() {
        return this.centroSaludServicioEspecialdiads;
    }
    
    public void setCentroSaludServicioEspecialdiads(Set<CentroSaludServicioEspecialdiad> centroSaludServicioEspecialdiads) {
        this.centroSaludServicioEspecialdiads = centroSaludServicioEspecialdiads;
    }
    public Set<PersonaTipoPersona> getPersonaTipoPersonas() {
        return this.personaTipoPersonas;
    }
    
    public void setPersonaTipoPersonas(Set<PersonaTipoPersona> personaTipoPersonas) {
        this.personaTipoPersonas = personaTipoPersonas;
    }
    public Set<RolServicio> getRolServicios() {
        return this.rolServicios;
    }
    
    public void setRolServicios(Set<RolServicio> rolServicios) {
        this.rolServicios = rolServicios;
    }




}


