package entidades;
// Generated 11-sep-2015 8:21:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ServicioEspecialidad generated by hbm2java
 */
public class ServicioEspecialidad  implements java.io.Serializable {


     private Integer idServicioEspecialidad;
     private Integer codServicio;
     private Integer codEspecialidad;
     private String nombre;
     private Set<CentroSaludServicioEspecialidad> centroSaludServicioEspecialidads = new HashSet<CentroSaludServicioEspecialidad>(0);
     private Set<PersonaTipoPersona> personaTipoPersonas = new HashSet<PersonaTipoPersona>(0);
     private Set<RolServicio> rolServicios = new HashSet<RolServicio>(0);

    public ServicioEspecialidad() {
    }

    public ServicioEspecialidad(Integer codServicio, Integer codEspecialidad, String nombre, Set<CentroSaludServicioEspecialidad> centroSaludServicioEspecialidads, Set<PersonaTipoPersona> personaTipoPersonas, Set<RolServicio> rolServicios) {
       this.codServicio = codServicio;
       this.codEspecialidad = codEspecialidad;
       this.nombre = nombre;
       this.centroSaludServicioEspecialidads = centroSaludServicioEspecialidads;
       this.personaTipoPersonas = personaTipoPersonas;
       this.rolServicios = rolServicios;
    }
   
    public Integer getIdServicioEspecialidad() {
        return this.idServicioEspecialidad;
    }
    
    public void setIdServicioEspecialidad(Integer idServicioEspecialidad) {
        this.idServicioEspecialidad = idServicioEspecialidad;
    }
    public Integer getCodServicio() {
        return this.codServicio;
    }
    
    public void setCodServicio(Integer codServicio) {
        this.codServicio = codServicio;
    }
    public Integer getCodEspecialidad() {
        return this.codEspecialidad;
    }
    
    public void setCodEspecialidad(Integer codEspecialidad) {
        this.codEspecialidad = codEspecialidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<CentroSaludServicioEspecialidad> getCentroSaludServicioEspecialidads() {
        return this.centroSaludServicioEspecialidads;
    }
    
    public void setCentroSaludServicioEspecialidads(Set<CentroSaludServicioEspecialidad> centroSaludServicioEspecialidads) {
        this.centroSaludServicioEspecialidads = centroSaludServicioEspecialidads;
    }
    public Set<PersonaTipoPersona> getPersonaTipoPersonas() {
        return this.personaTipoPersonas;
    }
    
    public void setPersonaTipoPersonas(Set<PersonaTipoPersona> personaTipoPersonas) {
        this.personaTipoPersonas = personaTipoPersonas;
    }
    public Set<RolServicio> getRolServicios() {
        return this.rolServicios;
    }
    
    public void setRolServicios(Set<RolServicio> rolServicios) {
        this.rolServicios = rolServicios;
    }




}


