package entidades;
// Generated 06-sep-2015 6:46:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoEmpleado generated by hbm2java
 */
public class TipoEmpleado  implements java.io.Serializable {


     private Integer idTipoEmpleado;
     private String tipoEmpleado;
     private Set<PersonaTipoPersona> personaTipoPersonas = new HashSet<PersonaTipoPersona>(0);

    public TipoEmpleado() {
    }

	
    public TipoEmpleado(String tipoEmpleado) {
        this.tipoEmpleado = tipoEmpleado;
    }
    public TipoEmpleado(String tipoEmpleado, Set<PersonaTipoPersona> personaTipoPersonas) {
       this.tipoEmpleado = tipoEmpleado;
       this.personaTipoPersonas = personaTipoPersonas;
    }
   
    public Integer getIdTipoEmpleado() {
        return this.idTipoEmpleado;
    }
    
    public void setIdTipoEmpleado(Integer idTipoEmpleado) {
        this.idTipoEmpleado = idTipoEmpleado;
    }
    public String getTipoEmpleado() {
        return this.tipoEmpleado;
    }
    
    public void setTipoEmpleado(String tipoEmpleado) {
        this.tipoEmpleado = tipoEmpleado;
    }
    public Set<PersonaTipoPersona> getPersonaTipoPersonas() {
        return this.personaTipoPersonas;
    }
    
    public void setPersonaTipoPersonas(Set<PersonaTipoPersona> personaTipoPersonas) {
        this.personaTipoPersonas = personaTipoPersonas;
    }




}


