package entidades;
// Generated 06-sep-2015 6:46:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPersona generated by hbm2java
 */
public class TipoPersona  implements java.io.Serializable {


     private Integer idTipoPersona;
     private String tipoPersona;
     private Set<PersonaTipoPersona> personaTipoPersonas = new HashSet<PersonaTipoPersona>(0);

    public TipoPersona() {
    }

	
    public TipoPersona(String tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public TipoPersona(String tipoPersona, Set<PersonaTipoPersona> personaTipoPersonas) {
       this.tipoPersona = tipoPersona;
       this.personaTipoPersonas = personaTipoPersonas;
    }
   
    public Integer getIdTipoPersona() {
        return this.idTipoPersona;
    }
    
    public void setIdTipoPersona(Integer idTipoPersona) {
        this.idTipoPersona = idTipoPersona;
    }
    public String getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(String tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public Set<PersonaTipoPersona> getPersonaTipoPersonas() {
        return this.personaTipoPersonas;
    }
    
    public void setPersonaTipoPersonas(Set<PersonaTipoPersona> personaTipoPersonas) {
        this.personaTipoPersonas = personaTipoPersonas;
    }




}


