package entidades;
// Generated 25-ago-2015 21:41:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Topico generated by hbm2java
 */
public class Topico  implements java.io.Serializable {


     private Integer idTopico;
     private HistoriaClinica historiaClinica;
     private Recetamedica recetamedica;
     private Usuario usuario;
     private Date horaIngreso;
     private String tipoTratamiento;
     private String otros;
     private Date horaSalida;

    public Topico() {
    }

	
    public Topico(HistoriaClinica historiaClinica, Recetamedica recetamedica, Usuario usuario) {
        this.historiaClinica = historiaClinica;
        this.recetamedica = recetamedica;
        this.usuario = usuario;
    }
    public Topico(HistoriaClinica historiaClinica, Recetamedica recetamedica, Usuario usuario, Date horaIngreso, String tipoTratamiento, String otros, Date horaSalida) {
       this.historiaClinica = historiaClinica;
       this.recetamedica = recetamedica;
       this.usuario = usuario;
       this.horaIngreso = horaIngreso;
       this.tipoTratamiento = tipoTratamiento;
       this.otros = otros;
       this.horaSalida = horaSalida;
    }
   
    public Integer getIdTopico() {
        return this.idTopico;
    }
    
    public void setIdTopico(Integer idTopico) {
        this.idTopico = idTopico;
    }
    public HistoriaClinica getHistoriaClinica() {
        return this.historiaClinica;
    }
    
    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }
    public Recetamedica getRecetamedica() {
        return this.recetamedica;
    }
    
    public void setRecetamedica(Recetamedica recetamedica) {
        this.recetamedica = recetamedica;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getHoraIngreso() {
        return this.horaIngreso;
    }
    
    public void setHoraIngreso(Date horaIngreso) {
        this.horaIngreso = horaIngreso;
    }
    public String getTipoTratamiento() {
        return this.tipoTratamiento;
    }
    
    public void setTipoTratamiento(String tipoTratamiento) {
        this.tipoTratamiento = tipoTratamiento;
    }
    public String getOtros() {
        return this.otros;
    }
    
    public void setOtros(String otros) {
        this.otros = otros;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }




}


