package entidades;
// Generated 06-sep-2015 6:46:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubigeo generated by hbm2java
 */
public class Ubigeo  implements java.io.Serializable {


     private Integer idUbigeo;
     private String codDepartamento;
     private String codProvincia;
     private String codDistrito;
     private String nombre;
     private Set<Admision> admisions = new HashSet<Admision>(0);
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Ubigeo() {
    }

	
    public Ubigeo(String codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public Ubigeo(String codDepartamento, String codProvincia, String codDistrito, String nombre, Set<Admision> admisions, Set<Persona> personas) {
       this.codDepartamento = codDepartamento;
       this.codProvincia = codProvincia;
       this.codDistrito = codDistrito;
       this.nombre = nombre;
       this.admisions = admisions;
       this.personas = personas;
    }
   
    public Integer getIdUbigeo() {
        return this.idUbigeo;
    }
    
    public void setIdUbigeo(Integer idUbigeo) {
        this.idUbigeo = idUbigeo;
    }
    public String getCodDepartamento() {
        return this.codDepartamento;
    }
    
    public void setCodDepartamento(String codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public String getCodProvincia() {
        return this.codProvincia;
    }
    
    public void setCodProvincia(String codProvincia) {
        this.codProvincia = codProvincia;
    }
    public String getCodDistrito() {
        return this.codDistrito;
    }
    
    public void setCodDistrito(String codDistrito) {
        this.codDistrito = codDistrito;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Admision> getAdmisions() {
        return this.admisions;
    }
    
    public void setAdmisions(Set<Admision> admisions) {
        this.admisions = admisions;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


