package entidades;
// Generated 11-sep-2015 8:21:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMilitar generated by hbm2java
 */
public class UnidadMilitar  implements java.io.Serializable {


     private Integer idUnidadMilitar;
     private String siglas;
     private String unidadMilitar;
     private Date fechaReg;
     private Set<Admision> admisions = new HashSet<Admision>(0);

    public UnidadMilitar() {
    }

    public UnidadMilitar(String siglas, String unidadMilitar, Date fechaReg, Set<Admision> admisions) {
       this.siglas = siglas;
       this.unidadMilitar = unidadMilitar;
       this.fechaReg = fechaReg;
       this.admisions = admisions;
    }
   
    public Integer getIdUnidadMilitar() {
        return this.idUnidadMilitar;
    }
    
    public void setIdUnidadMilitar(Integer idUnidadMilitar) {
        this.idUnidadMilitar = idUnidadMilitar;
    }
    public String getSiglas() {
        return this.siglas;
    }
    
    public void setSiglas(String siglas) {
        this.siglas = siglas;
    }
    public String getUnidadMilitar() {
        return this.unidadMilitar;
    }
    
    public void setUnidadMilitar(String unidadMilitar) {
        this.unidadMilitar = unidadMilitar;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<Admision> getAdmisions() {
        return this.admisions;
    }
    
    public void setAdmisions(Set<Admision> admisions) {
        this.admisions = admisions;
    }




}


