package entidades;
// Generated 25-ago-2015 21:41:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMilitar generated by hbm2java
 */
public class UnidadMilitar  implements java.io.Serializable {


     private Integer idUnidadMilitar;
     private String siglas;
     private String unidadMilitar;
     private Date fechaReg;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public UnidadMilitar() {
    }

    public UnidadMilitar(String siglas, String unidadMilitar, Date fechaReg, Set<Persona> personas) {
       this.siglas = siglas;
       this.unidadMilitar = unidadMilitar;
       this.fechaReg = fechaReg;
       this.personas = personas;
    }
   
    public Integer getIdUnidadMilitar() {
        return this.idUnidadMilitar;
    }
    
    public void setIdUnidadMilitar(Integer idUnidadMilitar) {
        this.idUnidadMilitar = idUnidadMilitar;
    }
    public String getSiglas() {
        return this.siglas;
    }
    
    public void setSiglas(String siglas) {
        this.siglas = siglas;
    }
    public String getUnidadMilitar() {
        return this.unidadMilitar;
    }
    
    public void setUnidadMilitar(String unidadMilitar) {
        this.unidadMilitar = unidadMilitar;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


