package entidades;
// Generated 11-sep-2015 8:21:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Persona persona;
     private Usuario usuario;
     private String usuario_1;
     private String password;
     private Date fechaReg;
     private Character estado;
     private Set<Antecedente> antecedentes = new HashSet<Antecedente>(0);
     private Set<Recetamedica> recetamedicas = new HashSet<Recetamedica>(0);
     private Set<His> hises = new HashSet<His>(0);
     private Set<Sexualidad> sexualidads = new HashSet<Sexualidad>(0);
     private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<Topico> topicos = new HashSet<Topico>(0);
     private Set<ExamenFisico> examenFisicos = new HashSet<ExamenFisico>(0);
     private Set<Admision> admisions = new HashSet<Admision>(0);
     private Set<HistoriaClinica> historiaClinicas = new HashSet<HistoriaClinica>(0);
     private Set<DetalleHis> detalleHises = new HashSet<DetalleHis>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Usuario() {
    }

    public Usuario(Persona persona, Usuario usuario, String usuario_1, String password, Date fechaReg, Character estado, Set<Antecedente> antecedentes, Set<Recetamedica> recetamedicas, Set<His> hises, Set<Sexualidad> sexualidads, Set<UsuarioRol> usuarioRols, Set<Persona> personas, Set<Topico> topicos, Set<ExamenFisico> examenFisicos, Set<Admision> admisions, Set<HistoriaClinica> historiaClinicas, Set<DetalleHis> detalleHises, Set<Usuario> usuarios) {
       this.persona = persona;
       this.usuario = usuario;
       this.usuario_1 = usuario_1;
       this.password = password;
       this.fechaReg = fechaReg;
       this.estado = estado;
       this.antecedentes = antecedentes;
       this.recetamedicas = recetamedicas;
       this.hises = hises;
       this.sexualidads = sexualidads;
       this.usuarioRols = usuarioRols;
       this.personas = personas;
       this.topicos = topicos;
       this.examenFisicos = examenFisicos;
       this.admisions = admisions;
       this.historiaClinicas = historiaClinicas;
       this.detalleHises = detalleHises;
       this.usuarios = usuarios;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getUsuario_1() {
        return this.usuario_1;
    }
    
    public void setUsuario_1(String usuario_1) {
        this.usuario_1 = usuario_1;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set<Antecedente> getAntecedentes() {
        return this.antecedentes;
    }
    
    public void setAntecedentes(Set<Antecedente> antecedentes) {
        this.antecedentes = antecedentes;
    }
    public Set<Recetamedica> getRecetamedicas() {
        return this.recetamedicas;
    }
    
    public void setRecetamedicas(Set<Recetamedica> recetamedicas) {
        this.recetamedicas = recetamedicas;
    }
    public Set<His> getHises() {
        return this.hises;
    }
    
    public void setHises(Set<His> hises) {
        this.hises = hises;
    }
    public Set<Sexualidad> getSexualidads() {
        return this.sexualidads;
    }
    
    public void setSexualidads(Set<Sexualidad> sexualidads) {
        this.sexualidads = sexualidads;
    }
    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
        this.usuarioRols = usuarioRols;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }
    public Set<Topico> getTopicos() {
        return this.topicos;
    }
    
    public void setTopicos(Set<Topico> topicos) {
        this.topicos = topicos;
    }
    public Set<ExamenFisico> getExamenFisicos() {
        return this.examenFisicos;
    }
    
    public void setExamenFisicos(Set<ExamenFisico> examenFisicos) {
        this.examenFisicos = examenFisicos;
    }
    public Set<Admision> getAdmisions() {
        return this.admisions;
    }
    
    public void setAdmisions(Set<Admision> admisions) {
        this.admisions = admisions;
    }
    public Set<HistoriaClinica> getHistoriaClinicas() {
        return this.historiaClinicas;
    }
    
    public void setHistoriaClinicas(Set<HistoriaClinica> historiaClinicas) {
        this.historiaClinicas = historiaClinicas;
    }
    public Set<DetalleHis> getDetalleHises() {
        return this.detalleHises;
    }
    
    public void setDetalleHises(Set<DetalleHis> detalleHises) {
        this.detalleHises = detalleHises;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


