package entidades;
// Generated 25-ago-2015 21:41:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UsuarioRol generated by hbm2java
 */
public class UsuarioRol  implements java.io.Serializable {


     private Integer idUsuarioRol;
     private Rol rol;
     private Usuario usuario;
     private Date fechaReg;

    public UsuarioRol() {
    }

	
    public UsuarioRol(Rol rol, Usuario usuario) {
        this.rol = rol;
        this.usuario = usuario;
    }
    public UsuarioRol(Rol rol, Usuario usuario, Date fechaReg) {
       this.rol = rol;
       this.usuario = usuario;
       this.fechaReg = fechaReg;
    }
   
    public Integer getIdUsuarioRol() {
        return this.idUsuarioRol;
    }
    
    public void setIdUsuarioRol(Integer idUsuarioRol) {
        this.idUsuarioRol = idUsuarioRol;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }




}


